### ISSUE TITLE
Add new method to the compiler to generate snippets in the new format

### ISSUE THREAD

**Issue by patriciobcs** [patriciobcs/solana-snippets#6]
The compiler is currently generating snippets in the Rust Analyzer format, add a new method to generate the in the [new format](https://github.com/patriciobcs/solana-snippets/blob/eb8f1b2a3926fd948903ca711f724d4bc8a2294b/resources/data/README.md) described as following.

### Id

The id is a unique identifier for the snippet. It is used to identify the snippet in the database (memento).

### ParentId

The parent id is the id of the parent snippet. It is used to build the tree structure of the snippets.

### LastId

The last id is the id of the last child snippet. It is used to build the tree structure of the snippets.

### Type

The type is used to determine the semantics of the element:

0. Root
1. Folder
2. VSCode Native Snippet
3. Rust Analyzer Snippet
4. Terminal Snippet
5. Comment

### Label

The label is the name of the snippet. It is used to display the snippet in the editor and sidebar.

### Content

The content is the actual content of the snippet. It is used to display the snippet in the editor.

## Tasks

- [x] Move the current Rust Analyzer generation to its own function
- [x] Add new function that using the data from Rust Analyzer generates the snippets in the new model
- [x] Output the snippets to the extension default snippets 
- [x] Add reset snippets command
- [x] Improve the new function to include the folders
